http:
 port: "8081"
 path: "validate"

access_key: "1754dc0529315e870bb7c46f1ef5e19b"

http.host:
  numverify: "apilayer.net"

db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "![S/80WVgPUvJHi3QllL0XRA==]"
  name: "customerPhoneInfo"
  